//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanSoftware.Models.VIEW
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LoanDBEntities : DbContext
    {
        public LoanDBEntities()
            : base("name=LoanDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VBranchLimit> VBranchLimits { get; set; }
        public virtual DbSet<VPendingList> VPendingLists { get; set; }
        public virtual DbSet<VMemberLoan> VMemberLoans { get; set; }
        public virtual DbSet<VForwardPendingList> VForwardPendingLists { get; set; }
    }
}
