//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanSoftware.Models.VIEW
{
    using System;
    using System.Collections.Generic;
    
    public partial class VBranchLimit
    {
        public string BranchName { get; set; }
        public string BranchCode { get; set; }
        public decimal BrLimit { get; set; }
        public int LimitID { get; set; }
    }
}
