//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanSoftware.Models.VIEW
{
    using System;
    using System.Collections.Generic;
    
    public partial class VForwardPendingList
    {
        public string BranchCode { get; set; }
        public int MID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string AplicantName { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string NID { get; set; }
        public string District { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<decimal> LoanAmountTotal { get; set; }
        public int FormID { get; set; }
        public int LimitID { get; set; }
        public string Expr1 { get; set; }
        public decimal BrLimit { get; set; }
        public string BranchName { get; set; }
    }
}
