//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanSoftware.Models.VIEW
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMemberLoan
    {
        public int MID { get; set; }
        public string ApprovalNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string MemberNo { get; set; }
        public string ShareNumber { get; set; }
        public Nullable<decimal> ShareAmount { get; set; }
        public string InvestmentNo { get; set; }
        public string AplicantName { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string NID { get; set; }
        public string Village { get; set; }
        public string PO { get; set; }
        public string PS { get; set; }
        public string District { get; set; }
        public string PresentAddress { get; set; }
        public string BusinessAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public string BusinessNature { get; set; }
        public string BusinessType { get; set; }
        public string MotiveofLoan { get; set; }
        public Nullable<System.DateTime> DateOwn { get; set; }
        public Nullable<System.DateTime> DateRent { get; set; }
        public Nullable<decimal> AmountRent { get; set; }
        public string NameRent { get; set; }
        public Nullable<decimal> OwnAmount { get; set; }
        public string MLFile { get; set; }
        public string LoanNo { get; set; }
        public string BranchCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public Nullable<decimal> MonthlyAvarageIncome { get; set; }
        public Nullable<decimal> DailySaleAmount { get; set; }
        public Nullable<decimal> DailyProfit { get; set; }
        public Nullable<decimal> DailyIncome { get; set; }
        public Nullable<decimal> MonthlySaleAmount { get; set; }
        public Nullable<decimal> MonthlyProfit { get; set; }
        public Nullable<decimal> MonthlyIncome { get; set; }
        public string MAccountNo { get; set; }
        public Nullable<decimal> AmountInAccount { get; set; }
        public Nullable<decimal> LoanAmountTotal { get; set; }
        public Nullable<int> LoanRecoveryDays { get; set; }
        public Nullable<System.DateTime> LoanProvideDate { get; set; }
        public Nullable<decimal> LoanInstallmentAmount { get; set; }
        public string LoanInstallment { get; set; }
        public string SoftwareLoanNo { get; set; }
        public string FieldNo { get; set; }
        public Nullable<int> BiMudaraba_BIID { get; set; }
        public Nullable<int> CurrentSaving_CUID { get; set; }
        public Nullable<int> Guarantor_GID { get; set; }
        public Nullable<int> OtherBank_OID { get; set; }
        public Nullable<int> RetentionProperty_JID { get; set; }
        public Nullable<int> TRInvestment_TID { get; set; }
        public int FormID { get; set; }
        public string BranchName { get; set; }
    }
}
