// <auto-generated />
namespace LoanSoftware.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class scrpt004 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(scrpt004));
        
        string IMigrationMetadata.Id
        {
            get { return "202105060850025_scrpt004"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
