// <auto-generated />
namespace LoanSoftware.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateMemverloaninfoaddnewfield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateMemverloaninfoaddnewfield));
        
        string IMigrationMetadata.Id
        {
            get { return "202105050845411_updateMemverloaninfoaddnewfield"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
